### ISSUE TITLE
Assertion on demo application when selecting custom placeholdersProvider

### ISSUE THREAD

**Issue by phimage** [HamzaGhazouani/HGPlaceholders#9]
Launch example
Go to table view tab
Select an another settings like Default2

Code executed
```
self.placeholderTableView?.placeholdersProvider = .default2
self.placeholderTableView?.reloadData()
```

The table content is static so no change.
_Maybe you want to make table model dynamic according to the placeholdersProvider elements.
Maybe the placeholder in `PlaceholdersProvider` must be accessible_

Then clic on the last table cell like, starwars or xib
In `PlaceholdersShowing.showCustomPlaceholder(with`
```
assertionFailure("Your placeholdersProvider is not configured correctly, no placeholder with key: \(key.value) found!")
```

**Comment by HamzaGhazouani** [comment]
Hi @phimage, 
Thanks for your question/remark.
The default provider does not have custom placeholder, so, when we try to show it, the assertion stop program execution and inform us that no placeholder with this key is available.
I keep this in the sample project, because I think it's better to show what happen if we try to show non-existing placeholder.
